#ifndef _APP_CONFIG_H
#define _APP_CONFIG_H

	
#define PRODUCTION_CODE 	0x80
#define USER_CODE 			0x40
#define BATTERY_MODE 		0x20

#define RTC_CHECK_MODE 		0x41
#define RTC_NO_CHECK_MODE	0x21
#define RTC_WRITE_MODE		0x31


#define CAL_DATA_LENGTH					34
#define EARTH_TAMPER_THRESHOLD  		625    
#define CUR_MISMATCH_TAMPER_THRESHOLD  	2000
#define BAT_EARTH_TAMPER_THRESHOLD  	2000
#define NM_THRESHOLD_VOLTAGE   			9000      // we should check rc tamper if we reduce this further
#define COM_THRESHOLD_VOLTAGE   		11500      // disable communication below this voltage
#define ND_RUN_AT_REF_THRESHOLD_U		19000

#define MIN_TAMPER_DETECTION_POWER		1000	//100 watts i.e 50 ma 
#define EARTH_TAMPER_I_THRESHOLD		625		//625mA
#define CUR_MISMATCH_TAMPER_I_THRESHOLD	2000	//2A


#define IMAX_CURRENT					60000
#define NM_CURRENT_THRESHOLD			900
#define OVER_LOAD_THRESHOLD				72000UL
//#define OVER_VOLTAGE_THRESHOLD			28800

#define IMAX_CURRENT_NM					70000
#define IMAX_FALSE_CURRENT_NM			75000UL
#define REF_I_FOR_METER					10000UL
#define MIN_DROP_U_TAMPER				500
#define TEMPERATURE_U_THD				7000
#define TEMPERATURE_L_THD				6000





#define CALIB_LENGTH					20
#define REF_U							24000UL
#define REF_I							10000UL
#define REF_P							240000UL
#define POWER_FAIL_DET_THRESHOLD		10	//1.0V
#define POWER_FAIL_DET_THRESHOLD_LEVEL1	1690	//120.0V

//#define STARTING_POWER_THRESHOLD_L		360
//#define STARTING_POWER_THRESHOLD_CONST	480
//#define STARTING_POWER_THRESHOLD_U		560
#define STARTING_POWER_THRESHOLD_L		160
#define STARTING_POWER_THRESHOLD_CONST	240
#define STARTING_POWER_THRESHOLD_U		360
#define STARTING_POWER_THRESHOLD_APP_U	300

//#define NO_LOAD_CURRENT_THRESHOLD	2
//#define CONST_LOW_POWER_THRESHOLD	280
#define COVER_OPEN_WAIT_TIME		0x400
#define POWER_FAIL_PERSIT_TIME		120
#define METER_CONSTANT				16	// for 2 decimal
#define FORCE_POWER_FAIL_THRESHOLD	POWER_FAIL_DET_THRESHOLD	//10000	//100V
#define EXIT_VOLTAGE_THRESHOLD		11000	//110V

#define RESTORE_VALUE_PFAIL_NORMAL	0
#define RESTORE_VALUE_PFAIL_RESET	5


#define METER_RATING_5_30		(0)
#define POWER_BASE_EARTH_DETECT	(0)

#define RCD_TAMPER_TERMINAL3	(1)
#define RCD_TAMPER_TERMINAL4	(1)
#define NM_HARD_TEST			(0)
#define LOG_NM_INFO				(0)
#define HARMONICS_CAL_ENABLE	(0)
#define HARMONICS_LIMIT			3
#define HARMONICS_WAIT_TIME		5
#if (defined(METER_RATING_5_30) && (METER_RATING_5_30 == 1))
#define ONE_SECOND_PULSE_VAL	112500UL
#else
#define ONE_SECOND_PULSE_VAL 	225000UL
#endif


// meter utility
#define GUJRAT_METER_0			(0)
//#define IS_VOLT_TIMER_ON		(0)
#define TATA_POWER_TYPE_1		(1)
#define TATA_POWER_TYPE_2		(0)
#define IS_DISPLAY_PUSH_LOCK	(1)
#define IS_DC_MAG_ENABLE		(1)
#define IS_PRODUCTION_MODE_ENABLED	(0)

#if (defined(TATA_POWER_TYPE_1) && (TATA_POWER_TYPE_1 == 1))
#define REF_U_FOR_METER					23000
#define REFERENCEVOLTAGE 				23UL
#define ND_UPPER_U_THRESHOLD			33250		//145%
#define ND_RESTORE_U_THRESOLD			26450		//115%
#define ND_RESTORE_I_THRESHOLD			950			//10%
#define LOW_U_RESTORE_THRESHOLD			18400		//80%
#define LOW_U_RESTORE_I_THRESHOLD		200			//2%
#define LOW_U_OCC_THRESHOLD				16100		//70%
#define LOW_U_OCC_I_THRESHOLD			200			//2%
#define IMAX_POWER						1380000UL

#else
#define REF_U_FOR_METER					24000
#define REFERENCEVOLTAGE 				24UL
#define ND_UPPER_U_THRESHOLD			33250		//145%
#define ND_RESTORE_U_THRESOLD			26450		//115%
#define ND_RESTORE_I_THRESHOLD			950			//10%
#define LOW_U_RESTORE_THRESHOLD			18400		//80%
#define LOW_U_RESTORE_I_THRESHOLD		200			//2%
#define LOW_U_OCC_THRESHOLD				16100		//70%
#define LOW_U_OCC_I_THRESHOLD			200			//2%
#define IMAX_POWER						1440000UL

#endif


#endif
